---
- name: Install fail2ban
  yum:
    name: fail2ban
    state: present
  when:
  - ansible_os_family == "RedHat"

- name: Install fail2ban
  apt:
    name: fail2ban
    state: present
  when:
  - ansible_os_family == "Debian"

- name: Start fail2ban service
  service:
    name: fail2ban
    state: started
    enabled: yes
