---
- name: Delete standard user
  user:
    name: '{{ item }}'
    state: absent
    remove: yes
    force: yes
  with_items: '{{ os_users }}'

- name: Remove cloud user sudo file
  ansible.builtin.file:
    path: /etc/sudoers.d/90-cloud-init-users
    state: absent

- name: Remove Raspberry Pi OS user sudo file
  ansible.builtin.file:
    path: /etc/sudoers.d/010_pi-nopasswd
    state: absent

- name: Delete default Cloud user from sudoers
  replace:
    path: /etc/sudoers
    regexp: '^({{item}}\s.*)'
    replace: '#\1'
  with_items: '{{ os_users }}'

